### ISSUE TITLE
ExpressionConverter always converted with ns0 namespace prefix

### ISSUE THREAD

**Issue by isukces** [AmmyUI/AmmyUI#20]
Following code 
```
    IsEnabled: bind UseCustomProperties 
        convert (bool x) => !x   
```

is translated using ns0 namespace prefix but ns0 is used for Telerik.Windows.Controls   i.e. 
```
      <ns0:RadComboBox xmlns:ns0="clr-namespace:Telerik.Windows.Controls;assembly=Telerik.Windows.Controls.Input" Grid.Row="0" Style="{StaticResource CoolDialogRadComboBoxFieldStyle}" Grid.Column="1" VerticalAlignment="Center" SelectionBoxTemplate="{StaticResource CoolSizeTemplate}" ItemTemplate="{StaticResource CoolSizeTemplate}">
        <ns0:RadComboBox.SelectedValue>
          <Binding Path="HoleSize"/>
        </ns0:RadComboBox.SelectedValue>
        <ns0:RadComboBox.ItemsSource>
          <Binding Path="HoleSizes"/>
        </ns0:RadComboBox.ItemsSource>
        <ns0:RadComboBox.IsEnabled>
          <Binding Path="UseCustomProperties" Converter="{x:Static ns0:ExpressionConverter.Instance}" ConverterParameter="&lt;expr id=&quot;0&quot;&gt;&lt;lambda isaction=&quot;False&quot;&gt;&lt;unary op=&quot;LogicalNegate&quot;&gt;&lt;parameter name=&quot;customProperties&quot; type=&quot;System.Boolean&quot; /&gt;&lt;/unary&gt;&lt;parameter name=&quot;customProperties&quot; type=&quot;System.Boolean&quot; /&gt;&lt;/lambda&gt;&lt;/expr&gt;"/>
        </ns0:RadComboBox.IsEnabled>
      </ns0:RadComboBox>
```

**Comment by ionoy** [comment]
Is `RadComboBox` inside alias right now?

**Comment by isukces** [comment]
Yes. The alias is defined as follows:
```
alias MyComboBox(row, selectedValue=none, itemsSource=none) {
        RadComboBox {
                Grid.Row: $row
                Style: resource "CoolDialogRadComboBoxFieldStyle"
                Grid.Column: "1"
                VerticalAlignment: "Center"
                SelectedValue: $selectedValue
                ItemsSource: $itemsSource
        }
}
```
and it is used like this
```
    @MyComboBox("0", bind "HoleSize", bind HoleSizes){
      SelectionBoxTemplate: resource "CoolSizeTemplate"
      ItemTemplate: resource "CoolSizeTemplate"
      IsEnabled: bind UseCustomProperties 
			    convert (bool customProperties) => !customProperties     
      Style: resource "CoolDialogRadComboBoxFieldStyle"
    }
```

**Comment by ionoy** [comment]
I'm on it. Will update package in hour or two and notify you.

**Comment by ionoy** [comment]
Should be fixed now!

I've uploaded new version to MyGet feed:

Nuget V3: https://www.myget.org/F/ammy/api/v3/index.json
Nuget V2: https://www.myget.org/F/ammy/api/v2

Add it to Options -> Nuget Package Manager -> Package Sources
Don't forget to click Update button there.

After that just switch Package Manager source to this new feed and update-package Ammy. You might need to restart visual studio, since it uses assemblies from a package.

**Comment by isukces** [comment]
Sorry. Still not good. I have
```
 Converter="{x:Static ns1:ExpressionConverter.Instance}"
```
while `clr-namespace:AmmySidekick;assembly=AmmySidekick` has ns3 prefix
